### PR TITLE
Adding www.merriam-webster.com due to tracker wall breakage on iOS

### PR DESCRIPTION
**Pull request by jonathanKingston**
https://app.asana.com/0/1200277586140538/1200291944240425/f

### CODE REVIEW

**Comment by kdzwinel** [comment]
Shouldn't all rules go into both files? https://github.com/duckduckgo/content-blocking-lists/blob/main/trackers-whitelist-temporary.txt . AFAIK safari ext is still using the old one.

**Comment by jonathanKingston** [comment]
Ah https://github.com/duckduckgo/privacy-essentials-safari/pull/13 is still open yeah. Let me diff them and update.

**Comment by jonathanKingston** [comment]
@kdzwinel done :)

**Comment by kdzwinel** [comment]
Thanks!

**Pull request merged**
